site_name: Organicity Tech Docs

pages:
  -  home: index.md
  -  architecture:
      -  Asset CRUD: AssetCRUD.md
      -  Asset Data Model: AssetDataModel.md
  -  services:
      -  Asset Discovery Service: AssetDiscoveryService.md
      -  Asset Annotation Service: annotations/AssetAnnotationService.md
      -  Experimenter Portal: ExperimenterPortal.md
      -  Federated Data Assets: FederatedDataAssets.md
      -  Urban Data Observatory: UrbanDataObservatory.md
  -  tutorials:
      -  How To Access Token: HowToAccessToken.md
      -  How To Authenticate An User: HowToAuthenticateAnUser.md
      -  How To Oc Site: HowToOcSite.md
      -  How To Push An Asset: HowToPushAnAsset.md
      -  How To Push An Asset To The Experimenter Site: HowToPushAnAssetToTheExperimenterSite.md
      -  How To Push An Asset To The Provider Site: HowToPushAnAssetToTheProviderSite.md
      -  How To Refresh Token: HowToRefreshToken.md
      -  How To Update Detele An Asset: HowToUpdateDeteleAnAsset.md
      -  How To Create Annotation Tags: annotations/tutorials/HowToCreateAnnotationTags.md
      -  How To Annotate An Asset: annotations/tutorials/HowToAnnotateAnAsset.md
      -  How To Annotate An Asset using Machine Learning: jamaica/tutorials/HowToAutomaticallyAnnotateAssets.md
  - tools:
      -  Sensinact: tools/sensinact/index.md
      -  TSmart: tools/tsmart/tsmart.md
      -  Smartphone Experimentation: tools/set/index.md
      -  Websockets: tools/websockets/index.md
      -  Scenarios: tools/scenarios/index.md
      -  Facility Manager: tools/facility-manager/index.md
#      -  Annotations: annotations/tool.md
#      -  JAMAiCA: jamaica/tool.md

extra:
    logo: '/images/oc_logo.png'
    site_short_name: Tech Docs
    links:
        - name: api's
          url: https://organicityeu.github.io/api/
        - name: status
          url: https://status.organicity.eu/
    license: ''
    project: "This project has received funding from the European Union's Horizon 2020 research and innovation program under the grant agreement No. 645198"
    footer_logo: '/images/logo_eu.png'

extra_css:
    - css/extra.css

extra_javascript:
    - api/static/js/cropbox-min.js

theme_dir: 'custom_theme'

# google_analytics: ['UA-36723568-3', 'mkdocs.org']

repo_url: https://github.com/organicityeu

theme: mkdocs
