site_name: Organicity Tech Docs

pages:
  -  Home: index.md
  -  Assets:
      -  Asset Data Model: AssetDataModel.md
      -  Asset CRUD: AssetCRUD.md
      -  Federated Data Assets: FederatedDataAssets.md
  -  Services:
      -  Asset Discovery Service: AssetDiscoveryService.md
      -  Asset Annotation Service: annotations/AssetAnnotationService.md
      -  Experimenter Portal: services/experimenter-portal/index.md
      -  Urban Data Observatory: UrbanDataObservatory.md
      -  Facility Manager: services/facility-manager/index.md
      -  Community Management: services/community-management/index.md
      -  Reputation Service: services/ReputationService.md
  -  Tutorials:
      -  How To Access Token: HowToAccessToken.md
      -  How To Authenticate An User: HowToAuthenticateAnUser.md
      -  How To Be An Oc Site: HowToOcSite.md
      -  How To Push An Asset: HowToPushAnAsset.md
      -  How To Push An Asset To The Experimenter Site: HowToPushAnAssetToTheExperimenterSite.md
      -  How To Push An Asset To The Provider Site: HowToPushAnAssetToTheProviderSite.md
      -  How To Refresh Token: HowToRefreshToken.md
      -  How To Update Detele An Asset: HowToUpdateDeteleAnAsset.md
      -  How To Create Annotation Tags: annotations/tutorials/HowToCreateAnnotationTags.md
      -  How To Annotate An Asset: annotations/tutorials/HowToAnnotateAnAsset.md
      -  How To Annotate An Asset using Machine Learning: jamaica/tutorials/HowToAutomaticallyAnnotateAssets.md
      -  How To Create A Sensing-on-the-Go Sensor: tools/set/tutorials/HowToCreateASensor.md
      -  How To Create A Sensing-on-the-Go Experiment: tools/set/tutorials/HowToCreateAExperiment.md
      -  How To Create Participation Metrics : HowToCreateParticipantMetrics.md
      -  OrganiCity API Tester Application: OrganiCityTesterAPI.md
  - Tools:
      -  Eclipse sensiNact: tools/sensinact/index.md
      -  TSmarT: tools/tsmart/tsmart.md
      -  Sensing on the Go: tools/set/index.md
      -  Websockets: tools/websockets/index.md
      -  Scenarios: tools/scenarios/index.md
      -  Tinkerspace: tools/tinkerspace/index.md
#      -  Annotations: annotations/tool.md
#      -  JAMAiCA: jamaica/tool.md

extra:
    logo: '/images/oc_logo.png'
    site_short_name: OrganiCity Tech Docs
    links:
        - name: APIS
          url: /api/
        - name: Status
          url: https://status.organicity.eu/
    license: ''
    project: "This project has received funding from the European Union's Horizon 2020 research and innovation program under the grant agreement No. 645198"
    footer_logo: '/images/logo_eu.png'

extra_css:
    - css/extra.css

extra_javascript:
    - api/static/js/cropbox-min.js

theme_dir: 'custom_theme'

# google_analytics: ['UA-36723568-3', 'mkdocs.org']

repo_url: https://github.com/organicityeu

theme: mkdocs
